//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Burger2Home_ISL_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.Burger = new HashSet<Burger>();
        }
    
        public int ingredient_id { get; set; }
        public string name { get; set; }
        public Nullable<int> categorie_id { get; set; }
        public Nullable<int> allergene_id { get; set; }
    
        public virtual Allergene Allergene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Burger> Burger { get; set; }
        public virtual Categorie Categorie { get; set; }
    }
}
