//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Burger2Home_ISL_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public int userGroup_id { get; set; }
        public int user_id { get; set; }
        public int groupe_id { get; set; }
    
        public virtual Groupe Groupe { get; set; }
        public virtual Users Users { get; set; }
    }
}
