<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="IngredientsList.aspx.cs" Inherits="Burger2Home_ISL_Project.IngredientsList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Titre" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Header" runat="server">
    <style type="text/css">
        .auto-style1 {
            height: 131px;
        }

        .auto-style2 {
            width: 58px;
        }

        .auto-style3 {
            height: 131px;
            width: 58px;
        }

        .auto-style4 {
            width: 909px;
        }

        .auto-style5 {
            height: 131px;
            width: 909px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentBody" runat="server">
    <table style="width: 100%;">
        <tr>
            <td class="auto-style2">&nbsp;</td>
            <td class="auto-style4">&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3"></td>
            <td class="auto-style5">
                <div class="grilleIngredients">
                    <asp:SqlDataSource ID="IngredientLibelle" runat="server"
                        ConnectionString="Data Source=PC\SQLEXPRESS;Initial Catalog=Burger2Home;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework"
                        ProviderName="System.Data.SqlClient" SelectCommand="SELECT Ingredient.* FROM Ingredient"></asp:SqlDataSource>
                    <div>
                        <asp:GridView ID="gridViewingredients" runat="server"
                            DataSourceID="ingredientLibelle" AllowSorting="True" DataKeyNames="ingredient_id"
                            HeaderStyle-CssClass="entetegrille"
                            AlternatingRowStyle-CssClass="lignesgrille"
                            BackColor="White"
                            BorderColor="#CC9966"
                            BorderStyle="Solid"
                            BorderWidth="4px"
                            CellPadding="4"
                            CellSpacing="2"
                         
                            AutoGenerateEditButton="True"
                            AutoGenerateSelectButton="True"
                            AutoGenerateDeleteButton="True"
                            AutoGenerateColumns="False">
                            <AlternatingRowStyle CssClass="lignesgrille"></AlternatingRowStyle>

                            <Columns>
                                <asp:BoundField DataField="ingredient_id" HeaderText="ID" SortExpression="ingredient_id" ReadOnly="true" />
                                <asp:BoundField DataField="ingredient_name" HeaderText="Name" SortExpression="ingredient_name"></asp:BoundField>
                                <asp:TemplateField HeaderText="Categorie" SortExpression="categorie_name">
                                    <ItemTemplate>
                                        <asp:Label ID="lblName" runat="server" Text='<%#DataBinder.Eval(Container.DataItem,"categorie_id") %>' />
                                        <%-- <%# Eval("categorie_id") %>--%>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Allergene" SortExpression="allergene_name">
                                    <ItemTemplate>
                                        <%#Eval("allergene_id") %>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>

                            <FooterStyle BackColor="#FFFFCC" ForeColor="#330099"></FooterStyle>

                            <HeaderStyle BackColor="#990000" CssClass="entetegrille" Font-Bold="True" ForeColor="#FFFFCC"></HeaderStyle>

                            <PagerStyle HorizontalAlign="Center" ForeColor="#330099" BackColor="#FFFFCC"></PagerStyle>

                            <RowStyle BackColor="White" ForeColor="#330099"></RowStyle>

                            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399"></SelectedRowStyle>

                            <SortedAscendingCellStyle BackColor="#FEFCEB"></SortedAscendingCellStyle>

                            <SortedAscendingHeaderStyle BackColor="#AF0101"></SortedAscendingHeaderStyle>

                            <SortedDescendingCellStyle BackColor="#F6F0C0"></SortedDescendingCellStyle>

                            <SortedDescendingHeaderStyle BackColor="#7E0000"></SortedDescendingHeaderStyle>
                        </asp:GridView>
                    </div>
                </div>
            </td>
            <td class="auto-style1"></td>
        </tr>
        <tr>
            <td class="auto-style2">&nbsp;</td>
            <td class="auto-style4">&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </table>
</asp:Content>
<%--BorderColor="#CC9966"--%>